config/routes.rb
Rails.application.routes.draw do

  resources :assignments

  resources :evaluations

  resources :teams
  
  resources :members do
    collection { post :import }
  end

  get 'student/index'

  get 'admin' => 'admin#index'
  get 'student' => 'student#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :members
  root :to => 'sessions#new'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  skip_before_action :admin_authorize, only: [:index, :show]
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:name, :description, :due_date)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.datetime_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: 'button small radius' %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Edit Assignment Form</h1>

<%= render 'form' %>

app/views/assignments/index.html.erb
<h1>Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Due date</th>
      <% if current_member.teacher %>
          <th colspan="3">Admin</th>
    <% end %>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.name %></td>
        <td><%= assignment.description %></td>
        <td><%= assignment.due_date %></td>
        <% if current_member.teacher %>
            <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
            <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_member.teacher %>
    <%= link_to 'New Assignment', new_assignment_path, class: 'button secondary small radius' %>
<% end %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assignment.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @assignment.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @assignment.due_date %>
</p>

<% if current_member.teacher %>
    <%= link_to 'Edit', edit_assignment_path(@assignment), class: 'button secondary small raidus' %>
<% end %>