config/routes.rb
Rails.application.routes.draw do

  resources :assignments

  resources :evaluations

  resources :teams
  
  resources :members do
    collection { post :import }
  end

  get 'student/index'

  get 'admin' => 'admin#index'
  get 'student' => 'student#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :members
  root :to => 'sessions#new'

end

app/views/shared/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
      <% if current_member %>
        <% if current_member.teacher %>
            <a href="/peer/admin">
        <% else %>
            <a href="/peer/student">
        <% end %>
      <% else %>
        <a href="/peer/login">
      <% end %>
        WMU Peer Evaluation</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon">
    <% if current_member %>
        <% if current_member.teacher %>
            <a href="<%= admin_path %>">
        <% else %>
            <a href="<%= student_path%>">
        <% end %>
    <% end %>
    <span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
    <% if current_member %>
      <li class="logmsg">Logged in as:<br /> <%= current_member.first %> <%= current_member.last %></li>
    <% end %>
      <li class="active"><%= link_to "Logout", logout_path %></li>

    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
    </ul>
  </section>
</nav>