config/routes.rb
Rails.application.routes.draw do

  resources :assignments

  resources :evaluations

  resources :teams
  
  resources :members do
    collection { post :import }
  end

  get 'student/index'

  get 'admin' => 'admin#index'
  get 'student' => 'student#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :members
  root :to => 'sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "WMU Peer Evaluation" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <%= render 'shared/navigation' %>
  <link rel="stylesheet" href="icons/foundation-icons.css" />

  <div id="bar">
    <% if flash[:alert] || flash[:notice] %>
        <p class="alert"><%= flash[:alert] %>
        <p class="notice"><%= flash[:notice] %>
    <% end %>

    <div id="controls">
      <% if current_member %>
          <% if current_member.teacher %>
              <%= link_to "Students", members_path, class: 'button success radius small' %>
              <%= link_to "Teams", teams_path, class: 'button success radius small' %>
              <%= link_to "Evaluations", evaluations_path, class: 'button success radius small' %>
              <%= link_to "Assignments", assignments_path, class: 'button success radius small' %>
          <% else %>
              <%= link_to "Assignments", assignments_path, class: 'button success radius small' %>
              <%= link_to "Show Evaluations", evaluations_path, class: 'button success radius small' %>
              <%= link_to "New Evaluation", new_evaluation_path, class: 'button success radius small' %>
          <% end %>
          <hr />
      <% end %>
    </div>
  </div>

  <div id="main">
       <%= yield %>
  </div>
  </body>

</html>