config/routes.rb
Rails.application.routes.draw do

  resources :assignments

  resources :evaluations

  resources :teams
  
  resources :members do
    collection { post :import }
  end

  get 'student/index'

  get 'admin' => 'admin#index'
  get 'student' => 'student#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :members
  root :to => 'sessions#new'

end

app/models/member.rb
class Member < ActiveRecord::Base
  require 'csv'
  validates :email, presence: true, uniqueness: true
  has_secure_password

  belongs_to :team
  has_many :evaluations

  def name_and_email 
    "#{first} #{last}, #{email}"
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      member_hash = row.to_hash
      member = Member.where(id: member_hash["id"])


      if member.cont == 1
        member.first.update_attributes(product_hash)
      else
        Member.create!(member_hash)
      end
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :update]
  skip_before_action :admin_authorize, only: [:new, :create, :update]

  # GET /members
  # GET /members.json
  def index
    @members = Member.order(:last)
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to login_url, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_url, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Member.import(params[:file])
    redirect_to member_index_url, notice: "Members imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:email, :password, :password_confirmation, :first, :last, :teacher)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
    <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% @member.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <fieldset>
      <legend>Enter Student Details</legend>

      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.label :first %><br>
        <%= f.text_field :first %>
      </div>
      <div class="field">
        <%= f.label :last %><br>
        <%= f.text_field :last %>
      </div>
      <%= f.hidden_field :teacher, :value => false %>
      <div class="actions">
        <%= f.submit "Register", class: 'button small radius' %>
      </div>
    </fieldset>
<% end %>

app/views/members/edit.html.erb
<h1>Edit Member Form</h1>

<%= render 'form' %>

app/views/members/index.html.erb
<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First</th>
      <th>Last</th>
      <th>Teacher</th>
      <th colspan="3">Admin</th>
    </tr>
  </thead>

  <tbody>

    <% @members.each do |member| %>
      <tr>
        <td><%= member.email %></td>
        <td><%= member.first %></td>
        <td><%= member.last %></td>
        <td><%= member.teacher %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>
<%= link_to 'New Member', new_member_path, class: 'button small radius secondary' %>


<%# <div> %>
<%# <h2>Import a CSV File</h2> %>
<%#  <%=form_tag import_products_path, multipart: true do %>
<%#    <%= file_field_tag :file %>
<%#    <%= submit_tag "Import CSV" %>
<%#  <% end %>
<%# </div> %>

app/views/members/new.html.erb
<h1>New Student Form</h1>

<%= render 'form' %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<p>
  <strong>First:</strong>
  <%= @member.first %>
</p>

<p>
  <strong>Last:</strong>
  <%= @member.last %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @member.teacher %>
</p>

<%= link_to 'Edit', edit_member_path(@member), class: 'button secondary small radius' %>